sudo pacman -S 0ad
sudo pacman -S 0ad-data
sudo pacman -S a52dec
sudo pacman -S aalib
sudo pacman -S abseil-cpp
sudo pacman -S accounts-qml-module
sudo pacman -S accountsservice
sudo pacman -S acl
sudo pacman -S acorn
sudo pacman -S acpi
sudo pacman -S acpi_call-lts
sudo pacman -S acpilight
sudo pacman -S acpitool
sudo pacman -S adapta-gtk-theme
sudo pacman -S adobe-source-code-pro-fonts
sudo pacman -S adobe-source-han-mono-cn-fonts
sudo pacman -S adobe-source-han-sans-cn-fonts
sudo pacman -S adobe-source-han-sans-otc-fonts
sudo pacman -S adobe-source-han-serif-cn-fonts
sudo pacman -S adwaita-icon-theme
sudo pacman -S aegisub
sudo pacman -S akonadi
sudo pacman -S akonadi-calendar
sudo pacman -S akonadi-calendar-tools
sudo pacman -S akonadi-contacts
sudo pacman -S akonadi-import-wizard
sudo pacman -S akonadi-mime
sudo pacman -S akonadi-notes
sudo pacman -S akonadi-search
sudo pacman -S akonadiconsole
sudo pacman -S akregator
sudo pacman -S alacritty
sudo pacman -S alembic
sudo pacman -S alpm_octopi_utils
sudo pacman -S alsa-card-profiles
sudo pacman -S alsa-firmware
sudo pacman -S alsa-lib
sudo pacman -S alsa-oss
sudo pacman -S alsa-plugins
sudo pacman -S alsa-tools
sudo pacman -S alsa-topology-conf
sudo pacman -S alsa-ucm-conf
sudo pacman -S alsa-utils
sudo pacman -S amd-ucode
sudo pacman -S amdvlk
sudo pacman -S amtk
sudo pacman -S analitza
sudo pacman -S android-tools
sudo pacman -S android-udev
sudo pacman -S anthy
sudo pacman -S anydesk-bin
sudo pacman -S aom
sudo pacman -S apache
sudo pacman -S appstream
sudo pacman -S appstream-glib
sudo pacman -S appstream-qt
sudo pacman -S apr
sudo pacman -S apr-util
sudo pacman -S arandr
sudo pacman -S arc-icon-theme
sudo pacman -S archlinux-appstream-data
sudo pacman -S archlinux-keyring
sudo pacman -S archlinuxcn-keyring
sudo pacman -S arctime
sudo pacman -S ardour
sudo pacman -S arduino
sudo pacman -S arduino-avr-core
sudo pacman -S arduino-builder
sudo pacman -S arduino-ctags
sudo pacman -S arduino-docs
sudo pacman -S argon2
sudo pacman -S aria2
sudo pacman -S aribb24
sudo pacman -S ark
sudo pacman -S artikulate
sudo pacman -S asciinema
sudo pacman -S asio
sudo pacman -S asp
sudo pacman -S aspell
sudo pacman -S at-spi2-atk
sudo pacman -S at-spi2-core
sudo pacman -S atk
sudo pacman -S atkmm
sudo pacman -S atop
sudo pacman -S attica
sudo pacman -S attr
sudo pacman -S aubio
sudo pacman -S audacity
sudo pacman -S audiocd-kio
sudo pacman -S audiofile
sudo pacman -S audit
sudo pacman -S autoconf
sudo pacman -S autoconf-archive
sudo pacman -S automake
sudo pacman -S avahi
sudo pacman -S avogadro-crystals
sudo pacman -S avogadro-molecules
sudo pacman -S avogadrolibs
sudo pacman -S avr-binutils
sudo pacman -S avr-gcc
sudo pacman -S avr-libc
sudo pacman -S avrdude
sudo pacman -S awesome-terminal-fonts
sudo pacman -S axel
sudo pacman -S babl
sudo pacman -S baloo
sudo pacman -S baloo-widgets
sudo pacman -S base
sudo pacman -S bash
sudo pacman -S bash-completion
sudo pacman -S bash-language-server
sudo pacman -S bashtop
sudo pacman -S bat
sudo pacman -S bc
sudo pacman -S bdf-unifont
sudo pacman -S bilibili-live-helper-bin
sudo pacman -S binutils
sudo pacman -S bison
sudo pacman -S black-hole-solver
sudo pacman -S blas
sudo pacman -S blender
sudo pacman -S blinken
sudo pacman -S blosc
sudo pacman -S bluedevil
sudo pacman -S bluez
sudo pacman -S bluez-libs
sudo pacman -S bluez-qt
sudo pacman -S bolt
sudo pacman -S bomber
sudo pacman -S boost
sudo pacman -S boost-libs
sudo pacman -S bovo
sudo pacman -S box2d
sudo pacman -S breeze
sudo pacman -S breeze-gtk
sudo pacman -S breeze-icons
sudo pacman -S bridge-utils
sudo pacman -S brltty
sudo pacman -S brotli
sudo pacman -S btrfs-progs
sudo pacman -S bubblewrap
sudo pacman -S bullet
sudo pacman -S bzip2
sudo pacman -S c-ares
sudo pacman -S ca-certificates
sudo pacman -S ca-certificates-mozilla
sudo pacman -S ca-certificates-utils
sudo pacman -S cabextract
sudo pacman -S cairo
sudo pacman -S cairomm
sudo pacman -S calendarsupport
sudo pacman -S cantarell-fonts
sudo pacman -S cantor
sudo pacman -S capnproto
sudo pacman -S catimg
sudo pacman -S cblas
sudo pacman -S ccls
sudo pacman -S cdparanoia
sudo pacman -S cdrtools
sudo pacman -S celt
sudo pacman -S ceph-libs
sudo pacman -S cervisia
sudo pacman -S cfitsio
sudo pacman -S cheese
sudo pacman -S chromaprint
sudo pacman -S chrpath
sudo pacman -S cifs-utils
sudo pacman -S clang
sudo pacman -S clucene
sudo pacman -S clutter
sudo pacman -S clutter-gst
sudo pacman -S clutter-gtk
sudo pacman -S cmake
sudo pacman -S cmatrix
sudo pacman -S cogl
sudo pacman -S colord
sudo pacman -S com.qq.im.deepin
sudo pacman -S com.qq.tim.spark
sudo pacman -S compiler-rt
sudo pacman -S confuse
sudo pacman -S containerd
sudo pacman -S convertlit
sudo pacman -S coordgen
sudo pacman -S coreutils
sudo pacman -S cowsay
sudo pacman -S cpio
sudo pacman -S cpupower
sudo pacman -S crda
sudo pacman -S cronie
sudo pacman -S cryptsetup
sudo pacman -S ctags
sudo pacman -S cups
sudo pacman -S cups-filters
sudo pacman -S curl
sudo pacman -S dav1d
sudo pacman -S davfs2
sudo pacman -S db
sudo pacman -S dbus
sudo pacman -S dbus-glib
sudo pacman -S dbus-python
sudo pacman -S dconf
sudo pacman -S ddcutil
sudo pacman -S debtap
sudo pacman -S deepin-udis86
sudo pacman -S deepin-wine-helper
sudo pacman -S deepin-wine-plugin
sudo pacman -S deepin-wine-plugin-virtual
sudo pacman -S deepin-wine5
sudo pacman -S deepin-wine5-i386
sudo pacman -S deepin.com.qq.im.light
sudo pacman -S desktop-file-utils
sudo pacman -S device-mapper
sudo pacman -S dhcp
sudo pacman -S dhcpcd
sudo pacman -S diffutils
sudo pacman -S discord
sudo pacman -S discount
sudo pacman -S discover
sudo pacman -S distorm
sudo pacman -S djvulibre
sudo pacman -S dkms
sudo pacman -S dmenu
sudo pacman -S dmidecode
sudo pacman -S dmraid
sudo pacman -S dnsmasq
sudo pacman -S dnssec-anchors
sudo pacman -S docbook-xml
sudo pacman -S docbook-xsl
sudo pacman -S docker
sudo pacman -S dolphin
sudo pacman -S dolphin-plugins
sudo pacman -S dosbox
sudo pacman -S dosfstools
sudo pacman -S dotnet-host
sudo pacman -S dotnet-runtime
sudo pacman -S dotnet-sdk
sudo pacman -S dotnet-targeting-pack
sudo pacman -S double-conversion
sudo pacman -S doxygen
sudo pacman -S drkonqi
sudo pacman -S droidcam
sudo pacman -S dtc
sudo pacman -S dune
sudo pacman -S dvdauthor
sudo pacman -S dvgrab
sudo pacman -S e2fsprogs
sudo pacman -S ebook-tools
sudo pacman -S eclipse-ecj
sudo pacman -S eclipse-emf
sudo pacman -S eclipse-platform
sudo pacman -S editorconfig-core-c
sudo pacman -S edk2-ovmf
sudo pacman -S efibootmgr
sudo pacman -S efivar
sudo pacman -S egl-wayland
sudo pacman -S eglexternalplatform
sudo pacman -S electron
sudo pacman -S electron-netease-cloud-music
sudo pacman -S elementary-icon-theme
sudo pacman -S elfutils
sudo pacman -S elisa
sudo pacman -S emacs-ctable
sudo pacman -S emacs-deferred
sudo pacman -S emacs-epc
sudo pacman -S emacs-git
sudo pacman -S embree
sudo pacman -S enca
sudo pacman -S enchant
sudo pacman -S enet
sudo pacman -S epherome
sudo pacman -S esp8266-nonos-sdk
sudo pacman -S esptool
sudo pacman -S ethtool
sudo pacman -S eventviews
sudo pacman -S exa
sudo pacman -S exempi
sudo pacman -S exfatprogs
sudo pacman -S exiv2
sudo pacman -S expat
sudo pacman -S extra-cmake-modules
sudo pacman -S f2fs-tools
sudo pacman -S faac
sudo pacman -S faad2
sudo pacman -S fail2ban
sudo pacman -S fakeroot
sudo pacman -S farstream
sudo pacman -S faudio
sudo pacman -S fcitx5
sudo pacman -S fcitx5-anthy
sudo pacman -S fcitx5-breeze
sudo pacman -S fcitx5-chewing
sudo pacman -S fcitx5-chinese-addons
sudo pacman -S fcitx5-configtool
sudo pacman -S fcitx5-gtk
sudo pacman -S fcitx5-material-color
sudo pacman -S fcitx5-pinyin-moegirl
sudo pacman -S fcitx5-pinyin-zhwiki
sudo pacman -S fcitx5-qt
sudo pacman -S fcitx5-rime
sudo pacman -S fd
sudo pacman -S feh
sudo pacman -S ffmpeg
sudo pacman -S ffmpegthumbs
sudo pacman -S ffms2
sudo pacman -S ffnvcodec-headers
sudo pacman -S fftw
sudo pacman -S figlet
sudo pacman -S file
sudo pacman -S filebrowser-bin
sudo pacman -S filelight
sudo pacman -S filesystem
sudo pacman -S findutils
sudo pacman -S fingerprint-gui
sudo pacman -S firefox
sudo pacman -S firewalld
sudo pacman -S flac
sudo pacman -S flameshot
sudo pacman -S flatpak
sudo pacman -S flex
sudo pacman -S flite
sudo pacman -S fltk
sudo pacman -S fluidsynth
sudo pacman -S fmt
sudo pacman -S fontconfig
sudo pacman -S fpc
sudo pacman -S fpc-src
sudo pacman -S fprintd
sudo pacman -S frameworkintegration
sudo pacman -S freecell-solver
sudo pacman -S freeglut
sudo pacman -S freeimage
sudo pacman -S freerdp
sudo pacman -S freetype2
sudo pacman -S frei0r-plugins
sudo pacman -S fribidi
sudo pacman -S frpc
sudo pacman -S fstrm
sudo pacman -S fuckmemory
sudo pacman -S fuse-common
sudo pacman -S fuse2
sudo pacman -S fuse3
sudo pacman -S fzf
sudo pacman -S gamemode
sudo pacman -S gavl
sudo pacman -S gawk
sudo pacman -S gc
sudo pacman -S gcab
sudo pacman -S gcc
sudo pacman -S gcc-libs
sudo pacman -S gconf
sudo pacman -S gcr
sudo pacman -S gd
sudo pacman -S gdb
sudo pacman -S gdb-common
sudo pacman -S gdbm
sudo pacman -S gdk-pixbuf2
sudo pacman -S gdl
sudo pacman -S gedit
sudo pacman -S gegl
sudo pacman -S geoclue
sudo pacman -S geocode-glib
sudo pacman -S geoip
sudo pacman -S geoip-database
sudo pacman -S gettext
sudo pacman -S gflags
sudo pacman -S ghostpcl
sudo pacman -S ghostscript
sudo pacman -S ghostxps
sudo pacman -S giblib
sudo pacman -S giflib
sudo pacman -S gimp
sudo pacman -S git
sudo pacman -S git-delta-git
sudo pacman -S git-lfs
sudo pacman -S github-cli
sudo pacman -S gl2ps
sudo pacman -S glew
sudo pacman -S glew1.10
sudo pacman -S glfw-wayland
sudo pacman -S glib-networking
sudo pacman -S glib2
sudo pacman -S glib2-docs
sudo pacman -S glibc
sudo pacman -S glibmm
sudo pacman -S glm
sudo pacman -S gloox
sudo pacman -S glslang
sudo pacman -S glu
sudo pacman -S glusterfs
sudo pacman -S gmp
sudo pacman -S gn-m85
sudo pacman -S gnome-autoar
sudo pacman -S gnome-common
sudo pacman -S gnome-desktop
sudo pacman -S gnome-icon-theme
sudo pacman -S gnome-icon-theme-symbolic
sudo pacman -S gnome-video-effects
sudo pacman -S gnugo
sudo pacman -S gnupg
sudo pacman -S gnutls
sudo pacman -S go
sudo pacman -S gobject-introspection
sudo pacman -S gobject-introspection-runtime
sudo pacman -S godot
sudo pacman -S google-chrome
sudo pacman -S google-glog
sudo pacman -S gopls
sudo pacman -S goverlay
sudo pacman -S gpart
sudo pacman -S gparted
sudo pacman -S gperf
sudo pacman -S gperftools
sudo pacman -S gpgme
sudo pacman -S gpm
sudo pacman -S gptfdisk
sudo pacman -S gradle
sudo pacman -S gradle-src
sudo pacman -S granatier
sudo pacman -S grantlee
sudo pacman -S grantlee-editor
sudo pacman -S grantleetheme
sudo pacman -S graphene
sudo pacman -S graphicsmagick
sudo pacman -S graphite
sudo pacman -S graphviz
sudo pacman -S grep
sudo pacman -S groff
sudo pacman -S groovy
sudo pacman -S grpc
sudo pacman -S grpc-cli
sudo pacman -S grub
sudo pacman -S grub-customizer
sudo pacman -S gsettings-desktop-schemas
sudo pacman -S gsfonts
sudo pacman -S gsl
sudo pacman -S gsm
sudo pacman -S gsmartcontrol
sudo pacman -S gspell
sudo pacman -S gssdp
sudo pacman -S gst-libav
sudo pacman -S gst-plugins-bad
sudo pacman -S gst-plugins-bad-libs
sudo pacman -S gst-plugins-base
sudo pacman -S gst-plugins-base-libs
sudo pacman -S gst-plugins-good
sudo pacman -S gstreamer
sudo pacman -S gtest
sudo pacman -S gtk-doc
sudo pacman -S gtk-update-icon-cache
sudo pacman -S gtk-vnc
sudo pacman -S gtk2
sudo pacman -S gtk3
sudo pacman -S gtk4
sudo pacman -S gtkglext
sudo pacman -S gtkmm
sudo pacman -S gtkmm3
sudo pacman -S gtksourceview4
sudo pacman -S gtkspell3
sudo pacman -S gtop
sudo pacman -S gts
sudo pacman -S guile
sudo pacman -S gumbo-parser
sudo pacman -S gupnp
sudo pacman -S gupnp-dlna
sudo pacman -S gupnp-igd
sudo pacman -S gv
sudo pacman -S gvfs
sudo pacman -S gwenview
sudo pacman -S gzip
sudo pacman -S harfbuzz
sudo pacman -S harfbuzz-icu
sudo pacman -S harvid
sudo pacman -S hdf5
sudo pacman -S hdparm
sudo pacman -S help2man
sudo pacman -S hicolor-icon-theme
sudo pacman -S hidapi
sudo pacman -S hiredis
sudo pacman -S hmcl
sudo pacman -S howdy
sudo pacman -S htop
sudo pacman -S http-parser
sudo pacman -S hugo
sudo pacman -S hunspell
sudo pacman -S hwids
sudo pacman -S hwinfo
sudo pacman -S hwloc
sudo pacman -S hyphen
sudo pacman -S i2c-tools
sudo pacman -S i3lock-color-git
sudo pacman -S r774.a318ff3-1
sudo pacman -S iana-etc
sudo pacman -S ibam
sudo pacman -S icoutils
sudo pacman -S icu
sudo pacman -S id3lib
sudo pacman -S ijs
sudo pacman -S imagemagick
sudo pacman -S imath
sudo pacman -S imlib2
sudo pacman -S incidenceeditor
sudo pacman -S iniparser
sudo pacman -S inkscape
sudo pacman -S intellij-idea-community-edition
sudo pacman -S intltool
sudo pacman -S iproute2
sudo pacman -S iptables-nft
sudo pacman -S iputils
sudo pacman -S ipython
sudo pacman -S iso-codes
sudo pacman -S itinerary
sudo pacman -S itstool
sudo pacman -S iw
sudo pacman -S jack2
sudo pacman -S jack2-dbus
sudo pacman -S jack_capture
sudo pacman -S jack_delay
sudo pacman -S jack_mixer
sudo pacman -S jack_utils
sudo pacman -S jansson
sudo pacman -S jasper
sudo pacman -S java-environment-common
sudo pacman -S java-runtime-common
sudo pacman -S java11-openjfx
sudo pacman -S java8-openjfx
sudo pacman -S jbig2dec
sudo pacman -S jbigkit
sudo pacman -S jdk-openjdk
sudo pacman -S jdk11-openjdk
sudo pacman -S jdk8-openjdk
sudo pacman -S jemalloc
sudo pacman -S jfsutils
sudo pacman -S joe
sudo pacman -S jq
sudo pacman -S jre-openjdk
sudo pacman -S jre-openjdk-headless
sudo pacman -S jre11-openjdk
sudo pacman -S jre11-openjdk-headless
sudo pacman -S jre8-openjdk
sudo pacman -S jre8-openjdk-headless
sudo pacman -S js78
sudo pacman -S json-c
sudo pacman -S json-glib
sudo pacman -S jsoncpp
sudo pacman -S juk
sudo pacman -S jxrlib
sudo pacman -S k3b
sudo pacman -S kaccounts-integration
sudo pacman -S kaccounts-providers
sudo pacman -S kactivities
sudo pacman -S kactivities-stats
sudo pacman -S kactivitymanagerd
sudo pacman -S kaddressbook
sudo pacman -S kajongg
sudo pacman -S kalarm
sudo pacman -S kalarmcal
sudo pacman -S kalgebra
sudo pacman -S kalzium
sudo pacman -S kamera
sudo pacman -S kamoso
sudo pacman -S kanagram
sudo pacman -S kapman
sudo pacman -S kapptemplate
sudo pacman -S karchive
sudo pacman -S kate
sudo pacman -S katomic
sudo pacman -S kauth
sudo pacman -S kbackup
sudo pacman -S kbd
sudo pacman -S kblackbox
sudo pacman -S kblocks
sudo pacman -S kbookmarks
sudo pacman -S kbounce
sudo pacman -S kbreakout
sudo pacman -S kbruch
sudo pacman -S kcachegrind
sudo pacman -S kcachegrind-common
sudo pacman -S kcalc
sudo pacman -S kcalendarcore
sudo pacman -S kcalutils
sudo pacman -S kcharselect
sudo pacman -S kcmutils
sudo pacman -S kcodecs
sudo pacman -S kcolorchooser
sudo pacman -S kcolorpicker
sudo pacman -S kcompletion
sudo pacman -S kconfig
sudo pacman -S kconfigwidgets
sudo pacman -S kcontacts
sudo pacman -S kcoreaddons
sudo pacman -S kcrash
sudo pacman -S kcron
sudo pacman -S kdav
sudo pacman -S kdbusaddons
sudo pacman -S kde-cli-tools
sudo pacman -S kde-dev-scripts
sudo pacman -S kde-dev-utils
sudo pacman -S kde-gtk-config
sudo pacman -S kdebugsettings
sudo pacman -S kdeclarative
sudo pacman -S kdeconnect
sudo pacman -S kdecoration
sudo pacman -S kded
sudo pacman -S kdeedu-data
sudo pacman -S kdegraphics-mobipocket
sudo pacman -S kdegraphics-thumbnailers
sudo pacman -S kdelibs4support
sudo pacman -S kdenetwork-filesharing
sudo pacman -S kdenlive
sudo pacman -S kdepim-addons
sudo pacman -S kdepim-runtime
sudo pacman -S kdeplasma-addons
sudo pacman -S kdesdk-kioslaves
sudo pacman -S kdesdk-thumbnailers
sudo pacman -S kdesu
sudo pacman -S kdevelop
sudo pacman -S kdevelop-php
sudo pacman -S kdf
sudo pacman -S kdiagram
sudo pacman -S kdialog
sudo pacman -S kdiamond
sudo pacman -S kdnssd
sudo pacman -S kdoctools
sudo pacman -S kdsoap
sudo pacman -S kdsoap-ws-discovery-client
sudo pacman -S git20200927-2
sudo pacman -S keditbookmarks
sudo pacman -S keepass
sudo pacman -S keepass-plugin-keeagent
sudo pacman -S keepassxc
sudo pacman -S kemoticons
sudo pacman -S keyutils
sudo pacman -S kfilemetadata
sudo pacman -S kfind
sudo pacman -S kfloppy
sudo pacman -S kfourinline
sudo pacman -S kgamma5
sudo pacman -S kgeography
sudo pacman -S kget
sudo pacman -S kglobalaccel
sudo pacman -S kgoldrunner
sudo pacman -S kgpg
sudo pacman -S kguiaddons
sudo pacman -S khangman
sudo pacman -S khelpcenter
sudo pacman -S kholidays
sudo pacman -S khotkeys
sudo pacman -S khtml
sudo pacman -S ki18n
sudo pacman -S kicad
sudo pacman -S kicad-library
sudo pacman -S kicad-library-3d
sudo pacman -S kiconthemes
sudo pacman -S kidentitymanagement
sudo pacman -S kidletime
sudo pacman -S kig
sudo pacman -S kigo
sudo pacman -S killbots
sudo pacman -S kimageannotator
sudo pacman -S kimagemapeditor
sudo pacman -S kimap
sudo pacman -S kindd
sudo pacman -S kinfocenter
sudo pacman -S kinit
sudo pacman -S kio
sudo pacman -S kio-extras
sudo pacman -S kio-fuse
sudo pacman -S kio-gdrive
sudo pacman -S kipi-plugins
sudo pacman -S kirigami-gallery
sudo pacman -S kirigami2
sudo pacman -S kiriki
sudo pacman -S kitemmodels
sudo pacman -S kitemviews
sudo pacman -S kiten
sudo pacman -S kitinerary
sudo pacman -S kjobwidgets
sudo pacman -S kjs
sudo pacman -S kjumpingcube
sudo pacman -S kldap
sudo pacman -S kleopatra
sudo pacman -S klettres
sudo pacman -S klickety
sudo pacman -S klines
sudo pacman -S kmag
sudo pacman -S kmahjongg
sudo pacman -S kmail
sudo pacman -S kmail-account-wizard
sudo pacman -S kmailtransport
sudo pacman -S kmbox
sudo pacman -S kmenuedit
sudo pacman -S kmime
sudo pacman -S kmines
sudo pacman -S kmix
sudo pacman -S kmod
sudo pacman -S kmousetool
sudo pacman -S kmouth
sudo pacman -S kmplot
sudo pacman -S knavalbattle
sudo pacman -S knetwalk
sudo pacman -S knewstuff
sudo pacman -S knights
sudo pacman -S knotes
sudo pacman -S knotifications
sudo pacman -S knotifyconfig
sudo pacman -S kolf
sudo pacman -S kollision
sudo pacman -S kolourpaint
sudo pacman -S kompare
sudo pacman -S konqueror
sudo pacman -S konquest
sudo pacman -S konsole
sudo pacman -S kontact
sudo pacman -S kontactinterface
sudo pacman -S konversation
sudo pacman -S kopeninghours
sudo pacman -S kopete
sudo pacman -S korganizer
sudo pacman -S kosmindoormap
sudo pacman -S kotlin
sudo pacman -S kpackage
sudo pacman -S kparts
sudo pacman -S kpat
sudo pacman -S kpeople
sudo pacman -S kpeoplevcard
sudo pacman -S kpimtextedit
sudo pacman -S kpkpass
sudo pacman -S kplotting
sudo pacman -S kpmcore
sudo pacman -S kpty
sudo pacman -S kpublictransport
sudo pacman -S kqtquickcharts
sudo pacman -S kquickcharts
sudo pacman -S krb5
sudo pacman -S krdc
sudo pacman -S kreversi
sudo pacman -S krfb
sudo pacman -S kross
sudo pacman -S kross-interpreters
sudo pacman -S kruler
sudo pacman -S krunner
sudo pacman -S kscreen
sudo pacman -S kscreenlocker
sudo pacman -S kservice
sudo pacman -S kshisen
sudo pacman -S ksirk
sudo pacman -S ksmtp
sudo pacman -S ksnakeduel
sudo pacman -S kspaceduel
sudo pacman -S ksquares
sudo pacman -S ksshaskpass
sudo pacman -S ksudoku
sudo pacman -S ksysguard
sudo pacman -S ksystemlog
sudo pacman -S ksystemstats
sudo pacman -S kteatime
sudo pacman -S ktexteditor
sudo pacman -S ktextwidgets
sudo pacman -S ktimer
sudo pacman -S ktnef
sudo pacman -S ktorrent
sudo pacman -S ktouch
sudo pacman -S ktuberling
sudo pacman -S kturtle
sudo pacman -S kubrick
sudo pacman -S kunitconversion
sudo pacman -S kuserfeedback
sudo pacman -S kwallet
sudo pacman -S kwallet-pam
sudo pacman -S kwalletmanager
sudo pacman -S kwave
sudo pacman -S kwayland
sudo pacman -S kwayland-integration
sudo pacman -S kwayland-server
sudo pacman -S kwidgetsaddons
sudo pacman -S kwin
sudo pacman -S kwindowsystem
sudo pacman -S kwordquiz
sudo pacman -S kwrite
sudo pacman -S kwrited
sudo pacman -S kxmlgui
sudo pacman -S l-smash
sudo pacman -S ladspa
sudo pacman -S lame
sudo pacman -S lapack
sudo pacman -S latte-dock-git
sudo pacman -S layer-shell-qt
sudo pacman -S lazarus
sudo pacman -S lazydocker
sudo pacman -S lcms2
sudo pacman -S ldb
sudo pacman -S ldns
sudo pacman -S lensfun
sudo pacman -S less
sudo pacman -S leveldb
sudo pacman -S lf
sudo pacman -S lib2geom
sudo pacman -S lib32-acl
sudo pacman -S lib32-alsa-lib
sudo pacman -S lib32-alsa-plugins
sudo pacman -S lib32-amdvlk
sudo pacman -S lib32-at-spi2-atk
sudo pacman -S lib32-at-spi2-core
sudo pacman -S lib32-atk
sudo pacman -S lib32-attr
sudo pacman -S lib32-brotli
sudo pacman -S lib32-bzip2
sudo pacman -S lib32-cairo
sudo pacman -S lib32-clang
sudo pacman -S lib32-colord
sudo pacman -S lib32-curl
sudo pacman -S lib32-dbus
sudo pacman -S lib32-dbus-glib
sudo pacman -S lib32-dconf
sudo pacman -S lib32-e2fsprogs
sudo pacman -S lib32-expat
sudo pacman -S lib32-faudio
sudo pacman -S lib32-flac
sudo pacman -S lib32-fluidsynth
sudo pacman -S lib32-fontconfig
sudo pacman -S lib32-freeglut
sudo pacman -S lib32-freetype2
sudo pacman -S lib32-fribidi
sudo pacman -S lib32-gcc-libs
sudo pacman -S lib32-gdk-pixbuf2
sudo pacman -S lib32-gettext
sudo pacman -S lib32-giflib
sudo pacman -S lib32-glew1.10
sudo pacman -S lib32-glib-networking
sudo pacman -S lib32-glib2
sudo pacman -S lib32-glibc
sudo pacman -S lib32-glu
sudo pacman -S lib32-gmp
sudo pacman -S lib32-gnutls
sudo pacman -S lib32-gst-plugins-base-libs
sudo pacman -S lib32-gstreamer
sudo pacman -S lib32-gtk2
sudo pacman -S lib32-gtk3
sudo pacman -S lib32-harfbuzz
sudo pacman -S lib32-icu
sudo pacman -S lib32-imlib2
sudo pacman -S lib32-jack2
sudo pacman -S lib32-jansson
sudo pacman -S lib32-json-glib
sudo pacman -S lib32-keyutils
sudo pacman -S lib32-krb5
sudo pacman -S lib32-l-smash
sudo pacman -S lib32-lcms2
sudo pacman -S lib32-libappindicator-gtk2
sudo pacman -S lib32-libappindicator-gtk3
sudo pacman -S lib32-libasyncns
sudo pacman -S lib32-libcaca
sudo pacman -S lib32-libcanberra
sudo pacman -S lib32-libcap
sudo pacman -S lib32-libcups
sudo pacman -S lib32-libcurl-compat
sudo pacman -S lib32-libcurl-gnutls
sudo pacman -S lib32-libdatrie
sudo pacman -S lib32-libdbusmenu-glib
sudo pacman -S lib32-libdbusmenu-gtk2
sudo pacman -S lib32-libdbusmenu-gtk3
sudo pacman -S lib32-libdrm
sudo pacman -S lib32-libelf
sudo pacman -S lib32-libepoxy
sudo pacman -S lib32-libffi
sudo pacman -S lib32-libgcrypt
sudo pacman -S lib32-libgcrypt15
sudo pacman -S lib32-libglvnd
sudo pacman -S lib32-libgpg-error
sudo pacman -S lib32-libgudev
sudo pacman -S lib32-libgusb
sudo pacman -S lib32-libice
sudo pacman -S lib32-libid3tag
sudo pacman -S lib32-libidn11
sudo pacman -S lib32-libidn2
sudo pacman -S lib32-libindicator-gtk2
sudo pacman -S lib32-libindicator-gtk3
sudo pacman -S lib32-libinstpatch
sudo pacman -S lib32-libjpeg-turbo
sudo pacman -S lib32-libjpeg6-turbo
sudo pacman -S lib32-libldap
sudo pacman -S lib32-libltdl
sudo pacman -S lib32-libmikmod
sudo pacman -S lib32-libmodplug
sudo pacman -S lib32-libnl
sudo pacman -S lib32-libnm
sudo pacman -S lib32-libnsl
sudo pacman -S lib32-libogg
sudo pacman -S lib32-libpcap
sudo pacman -S lib32-libpciaccess
sudo pacman -S lib32-libpng
sudo pacman -S lib32-libpng12
sudo pacman -S lib32-libproxy
sudo pacman -S lib32-libpsl
sudo pacman -S lib32-libpulse
sudo pacman -S lib32-librsvg
sudo pacman -S lib32-librtmp0
sudo pacman -S lib32-libsm
sudo pacman -S lib32-libsndfile
sudo pacman -S lib32-libsoup
sudo pacman -S lib32-libssh2
sudo pacman -S lib32-libtasn1
sudo pacman -S lib32-libthai
sudo pacman -S lib32-libtheora
sudo pacman -S lib32-libtiff
sudo pacman -S lib32-libtiff4
sudo pacman -S lib32-libtirpc
sudo pacman -S lib32-libudev0-shim
sudo pacman -S lib32-libunistring
sudo pacman -S lib32-libunwind
sudo pacman -S lib32-libusb
sudo pacman -S lib32-libva
sudo pacman -S lib32-libva-mesa-driver
sudo pacman -S lib32-libvdpau
sudo pacman -S lib32-libvorbis
sudo pacman -S lib32-libvpx1.3
sudo pacman -S lib32-libwebp
sudo pacman -S lib32-libwrap
sudo pacman -S lib32-libx11
sudo pacman -S lib32-libxau
sudo pacman -S lib32-libxcb
sudo pacman -S lib32-libxcomposite
sudo pacman -S lib32-libxcrypt
sudo pacman -S lib32-libxcursor
sudo pacman -S lib32-libxdamage
sudo pacman -S lib32-libxdmcp
sudo pacman -S lib32-libxext
sudo pacman -S lib32-libxfixes
sudo pacman -S lib32-libxft
sudo pacman -S lib32-libxi
sudo pacman -S lib32-libxinerama
sudo pacman -S lib32-libxkbcommon
sudo pacman -S lib32-libxml2
sudo pacman -S lib32-libxmu
sudo pacman -S lib32-libxrandr
sudo pacman -S lib32-libxrender
sudo pacman -S lib32-libxshmfence
sudo pacman -S lib32-libxslt
sudo pacman -S lib32-libxss
sudo pacman -S lib32-libxt
sudo pacman -S lib32-libxtst
sudo pacman -S lib32-libxv
sudo pacman -S lib32-libxxf86vm
sudo pacman -S lib32-llvm
sudo pacman -S lib32-llvm-libs
sudo pacman -S lib32-lm_sensors
sudo pacman -S lib32-lz4
sudo pacman -S lib32-mesa
sudo pacman -S lib32-mesa-vdpau
sudo pacman -S lib32-mpg123
sudo pacman -S lib32-ncurses
sudo pacman -S lib32-nettle
sudo pacman -S lib32-nspr
sudo pacman -S lib32-nss
sudo pacman -S lib32-ocl-icd
sudo pacman -S lib32-openal
sudo pacman -S lib32-opencl-mesa
sudo pacman -S lib32-opencl-nvidia
sudo pacman -S lib32-openssl
sudo pacman -S lib32-openssl-1.0
sudo pacman -S lib32-opus
sudo pacman -S lib32-orc
sudo pacman -S lib32-p11-kit
sudo pacman -S lib32-pam
sudo pacman -S lib32-pango
sudo pacman -S lib32-pcre
sudo pacman -S lib32-pipewire
sudo pacman -S lib32-pipewire-jack
sudo pacman -S lib32-pixman
sudo pacman -S lib32-polkit
sudo pacman -S lib32-portaudio
sudo pacman -S lib32-readline
sudo pacman -S lib32-rest
sudo pacman -S lib32-sdl
sudo pacman -S lib32-sdl2
sudo pacman -S lib32-sdl2_image
sudo pacman -S lib32-sdl2_mixer
sudo pacman -S lib32-sdl2_ttf
sudo pacman -S lib32-sdl_image
sudo pacman -S lib32-sdl_mixer
sudo pacman -S lib32-sdl_ttf
sudo pacman -S lib32-smpeg
sudo pacman -S lib32-sqlite
sudo pacman -S lib32-systemd
sudo pacman -S lib32-tdb
sudo pacman -S lib32-util-linux
sudo pacman -S lib32-v4l-utils
sudo pacman -S lib32-vkd3d
sudo pacman -S lib32-vulkan-icd-loader
sudo pacman -S lib32-vulkan-radeon
sudo pacman -S lib32-wayland
sudo pacman -S lib32-x264
sudo pacman -S lib32-xz
sudo pacman -S lib32-zlib
sudo pacman -S lib32-zstd
sudo pacman -S libabw
sudo pacman -S libaccounts-glib
sudo pacman -S libaccounts-qt
sudo pacman -S libaec
sudo pacman -S libaio
sudo pacman -S libakonadi
sudo pacman -S libappindicator-gtk3
sudo pacman -S libarchive
sudo pacman -S libass
sudo pacman -S libassuan
sudo pacman -S libasyncns
sudo pacman -S libatasmart
sudo pacman -S libatomic_ops
sudo pacman -S libavc1394
sudo pacman -S libavif
sudo pacman -S libavtp
sudo pacman -S libblockdev
sudo pacman -S libbluray
sudo pacman -S libbpf
sudo pacman -S libbs2b
sudo pacman -S libbsd
sudo pacman -S libburn
sudo pacman -S libbytesize
sudo pacman -S libcaca
sudo pacman -S libcacard
sudo pacman -S libcanberra
sudo pacman -S libcap
sudo pacman -S libcap-ng
sudo pacman -S libcddb
sudo pacman -S libcdio
sudo pacman -S libcdio-paranoia
sudo pacman -S libcdr
sudo pacman -S libchewing
sudo pacman -S libclc
sudo pacman -S libcloudproviders
sudo pacman -S libcmis
sudo pacman -S libcolord
sudo pacman -S libconfig
sudo pacman -S libcroco
sudo pacman -S libcue
sudo pacman -S libcups
sudo pacman -S libcurl-compat
sudo pacman -S libcurl-gnutls
sudo pacman -S libdaemon
sudo pacman -S libdatrie
sudo pacman -S libdbusmenu-glib
sudo pacman -S libdbusmenu-gtk2
sudo pacman -S libdbusmenu-gtk3
sudo pacman -S libdbusmenu-qt5
sudo pacman -S libdc1394
sudo pacman -S libdca
sudo pacman -S libde265
sudo pacman -S libdmtx
sudo pacman -S libdrm
sudo pacman -S libdv
sudo pacman -S libdvbpsi
sudo pacman -S libdvdnav
sudo pacman -S libdvdread
sudo pacman -S libe-book
sudo pacman -S libebml
sudo pacman -S libebur128
sudo pacman -S libedit
sudo pacman -S libelf
sudo pacman -S libepoxy
sudo pacman -S libepubgen
sudo pacman -S libetonyek
sudo pacman -S libev
sudo pacman -S libevdev
sudo pacman -S libevent
sudo pacman -S libexif
sudo pacman -S libexttextcat
sudo pacman -S libfakekey
sudo pacman -S libfdk-aac
sudo pacman -S libffi
sudo pacman -S libfontenc
sudo pacman -S libfprint
sudo pacman -S libfprint-1
sudo pacman -S libfreeaptx
sudo pacman -S libfreehand
sudo pacman -S libftdi
sudo pacman -S libgaminggear
sudo pacman -S libgcrypt
sudo pacman -S libgcrypt15
sudo pacman -S libgdiplus
sudo pacman -S libgee
sudo pacman -S libgexiv2
sudo pacman -S libgig
sudo pacman -S libgit2
sudo pacman -S libglvnd
sudo pacman -S libgme
sudo pacman -S libgpg-error
sudo pacman -S libgphoto2
sudo pacman -S libgravatar
sudo pacman -S libgrss
sudo pacman -S libgsf
sudo pacman -S libgssglue
sudo pacman -S libgtop
sudo pacman -S libgudev
sudo pacman -S libgusb
sudo pacman -S libgxps
sudo pacman -S libhandy
sudo pacman -S libheif
sudo pacman -S libibus
sudo pacman -S libical
sudo pacman -S libice
sudo pacman -S libid3tag
sudo pacman -S libidn
sudo pacman -S libidn11
sudo pacman -S libidn2
sudo pacman -S libiec61883
sudo pacman -S libieee1284
sudo pacman -S libimagequant
sudo pacman -S libime
sudo pacman -S libimobiledevice
sudo pacman -S libindicator-gtk2
sudo pacman -S libindicator-gtk3
sudo pacman -S libinih
sudo pacman -S libinput
sudo pacman -S libinput-gestures
sudo pacman -S libinput_gestures_qt
sudo pacman -S libinstpatch
sudo pacman -S libiptcdata
sudo pacman -S libiscsi
sudo pacman -S libixion
sudo pacman -S libjpeg-turbo
sudo pacman -S libjpeg6-turbo
sudo pacman -S libkate
sudo pacman -S libkcddb
sudo pacman -S libkcompactdisc
sudo pacman -S libkdcraw
sudo pacman -S libkdegames
sudo pacman -S libkdepim
sudo pacman -S libkeduvocdocument
sudo pacman -S libkexiv2
sudo pacman -S libkgapi
sudo pacman -S libkipi
sudo pacman -S libkleo
sudo pacman -S libkmahjongg
sudo pacman -S libkolabxml
sudo pacman -S libkomparediff2
sudo pacman -S libksane
sudo pacman -S libksba
sudo pacman -S libkscreen
sudo pacman -S libksieve
sudo pacman -S libksysguard
sudo pacman -S libktorrent
sudo pacman -S liblangtag
sudo pacman -S libldac
sudo pacman -S libldap
sudo pacman -S liblo
sudo pacman -S liblouis
sudo pacman -S liblqr
sudo pacman -S liblrdf
sudo pacman -S libltc
sudo pacman -S libluv
sudo pacman -S libmad
sudo pacman -S libmanette
sudo pacman -S libmatroska
sudo pacman -S libmbim
sudo pacman -S libmd
sudo pacman -S libmfx
sudo pacman -S libmicrodns
sudo pacman -S libmicrohttpd
sudo pacman -S libmikmod
sudo pacman -S libmm-glib
sudo pacman -S libmms
sudo pacman -S libmng
sudo pacman -S libmnl
sudo pacman -S libmodplug
sudo pacman -S libmp4v2
sudo pacman -S libmpc
sudo pacman -S libmpcdec
sudo pacman -S libmpeg2
sudo pacman -S libmspub
sudo pacman -S libmsym
sudo pacman -S libmtp
sudo pacman -S libmusicbrainz5
sudo pacman -S libmwaw
sudo pacman -S libmypaint
sudo pacman -S libnautilus-extension
sudo pacman -S libndp
sudo pacman -S libnet
sudo pacman -S libnetfilter_conntrack
sudo pacman -S libnewt
sudo pacman -S libnfnetlink
sudo pacman -S libnfs
sudo pacman -S libnftnl
sudo pacman -S libnghttp2
sudo pacman -S libnice
sudo pacman -S libnl
sudo pacman -S libnm
sudo pacman -S libnma
sudo pacman -S libnotify
sudo pacman -S libnsl
sudo pacman -S libnumbertext
sudo pacman -S libodfgen
sudo pacman -S libofa
sudo pacman -S libogg
sudo pacman -S libomxil-bellagio
sudo pacman -S liborcus
sudo pacman -S libosinfo
sudo pacman -S libotf
sudo pacman -S libotr
sudo pacman -S libp11-kit
sudo pacman -S libpagemaker
sudo pacman -S libpaper
sudo pacman -S libpcap
sudo pacman -S libpciaccess
sudo pacman -S libpeas
sudo pacman -S libpgm
sudo pacman -S libphonenumber
sudo pacman -S libpipeline
sudo pacman -S libplacebo
sudo pacman -S libplist
sudo pacman -S libpng
sudo pacman -S libpng12
sudo pacman -S libportal
sudo pacman -S libproxy
sudo pacman -S libpsl
sudo pacman -S libpulse
sudo pacman -S libqaccessibilityclient
sudo pacman -S libqalculate
sudo pacman -S libqmi
sudo pacman -S libqrtr-glib
sudo pacman -S libquicktime
sudo pacman -S libquvi
sudo pacman -S libquvi-scripts
sudo pacman -S libqxp
sudo pacman -S libraqm
sudo pacman -S libraw
sudo pacman -S libraw1394
sudo pacman -S libreoffice-fresh
sudo pacman -S librevenge
sudo pacman -S librime
sudo pacman -S librime-data
sudo pacman -S librsvg
sudo pacman -S librtmp0
sudo pacman -S libsamplerate
sudo pacman -S libsasl
sudo pacman -S libseccomp
sudo pacman -S libsecret
sudo pacman -S libshout
sudo pacman -S libsigc++
sudo pacman -S libsignon-glib
sudo pacman -S libslirp
sudo pacman -S libsm
sudo pacman -S libsndfile
sudo pacman -S libsodium
sudo pacman -S libsoup
sudo pacman -S libsoxr
sudo pacman -S libspectre
sudo pacman -S libspeechd
sudo pacman -S libspiro
sudo pacman -S libspnav
sudo pacman -S libsrtp
sudo pacman -S libssh
sudo pacman -S libssh2
sudo pacman -S libstaroffice
sudo pacman -S libstdc++5
sudo pacman -S libstemmer
sudo pacman -S libtar
sudo pacman -S libtasn1
sudo pacman -S libteam
sudo pacman -S libtermkey
sudo pacman -S libtg_owt
sudo pacman -S libthai
sudo pacman -S libtheora
sudo pacman -S libtiff
sudo pacman -S libtiff4
sudo pacman -S libtirpc
sudo pacman -S libtommath
sudo pacman -S libtool
sudo pacman -S libudev0-shim
sudo pacman -S libunistring
sudo pacman -S libunwind
sudo pacman -S libupnp
sudo pacman -S liburcu
sudo pacman -S liburing
sudo pacman -S libusb
sudo pacman -S libusb-compat
sudo pacman -S libusbmuxd
sudo pacman -S libutempter
sudo pacman -S libuv
sudo pacman -S libva
sudo pacman -S libva-mesa-driver
sudo pacman -S libvdpau
sudo pacman -S libvirt
sudo pacman -S libvirt-glib
sudo pacman -S libvirt-python
sudo pacman -S libvisio
sudo pacman -S libvisual
sudo pacman -S libvncserver
sudo pacman -S libvorbis
sudo pacman -S libvpx
sudo pacman -S libvpx1.3
sudo pacman -S libvterm
sudo pacman -S libwacom
sudo pacman -S libwebp
sudo pacman -S libwebsockets
sudo pacman -S libwmf
sudo pacman -S libwpd
sudo pacman -S libwpe
sudo pacman -S libwpg
sudo pacman -S libwps
sudo pacman -S libwrap
sudo pacman -S libx11
sudo pacman -S libx86
sudo pacman -S libx86emu
sudo pacman -S libxau
sudo pacman -S libxaw
sudo pacman -S libxcb
sudo pacman -S libxcomposite
sudo pacman -S libxcrypt
sudo pacman -S libxcursor
sudo pacman -S libxdamage
sudo pacman -S libxdg-basedir
sudo pacman -S libxdmcp
sudo pacman -S libxext
sudo pacman -S libxfce4ui
sudo pacman -S libxfce4util
sudo pacman -S libxfixes
sudo pacman -S libxfont2
sudo pacman -S libxft
sudo pacman -S libxi
sudo pacman -S libxinerama
sudo pacman -S libxkbcommon
sudo pacman -S libxkbcommon-x11
sudo pacman -S libxkbfile
sudo pacman -S libxklavier
sudo pacman -S libxml2
sudo pacman -S libxmu
sudo pacman -S libxnvctrl
sudo pacman -S libxpm
sudo pacman -S libxrandr
sudo pacman -S libxrender
sudo pacman -S libxres
sudo pacman -S libxshmfence
sudo pacman -S libxslt
sudo pacman -S libxss
sudo pacman -S libxt
sudo pacman -S libxtst
sudo pacman -S libxv
sudo pacman -S libxvmc
sudo pacman -S libxxf86vm
sudo pacman -S libyaml
sudo pacman -S libyuv
sudo pacman -S r2212+dfaf7534-2
sudo pacman -S libzip
sudo pacman -S libzmf
sudo pacman -S licenses
sudo pacman -S lightdm
sudo pacman -S lightdm-gtk-greeter
sudo pacman -S lightdm-gtk-greeter-settings
sudo pacman -S lightly-qt
sudo pacman -S lilv
sudo pacman -S linux-api-headers
sudo pacman -S linux-firmware
sudo pacman -S linux-headers
sudo pacman -S linux-lts
sudo pacman -S linux-lts-headers
sudo pacman -S linuxqq
sudo pacman -S lirc
sudo pacman -S lld
sudo pacman -S lldb
sudo pacman -S llpp
sudo pacman -S llvm
sudo pacman -S llvm-libs
sudo pacman -S lm_sensors
sudo pacman -S lmdb
sudo pacman -S lmms
sudo pacman -S log4cplus
sudo pacman -S lokalize
sudo pacman -S lolcat
sudo pacman -S lpsolve
sudo pacman -S lrzsz
sudo pacman -S lsb-release
sudo pacman -S lsd
sudo pacman -S lskat
sudo pacman -S lsof
sudo pacman -S lua
sudo pacman -S lua52
sudo pacman -S lua52-bitop
sudo pacman -S lua52-expat
sudo pacman -S lua52-lpeg
sudo pacman -S lua52-luajson
sudo pacman -S lua52-socket
sudo pacman -S lua53
sudo pacman -S luajit
sudo pacman -S lunar-client
sudo pacman -S lutris
sudo pacman -S lvm2
sudo pacman -S lxappearance
sudo pacman -S lz4
sudo pacman -S lzo
sudo pacman -S m17n-db
sudo pacman -S m17n-lib
sudo pacman -S m4
sudo pacman -S maeparser
sudo pacman -S mailcap
sudo pacman -S mailcommon
sudo pacman -S mailimporter
sudo pacman -S make
sudo pacman -S mallard-ducktype
sudo pacman -S man-db
sudo pacman -S mangohud
sudo pacman -S mangohud-common
sudo pacman -S marble
sudo pacman -S marble-common
sudo pacman -S mariadb
sudo pacman -S mariadb-clients
sudo pacman -S mariadb-libs
sudo pacman -S marisa
sudo pacman -S markdownpart
sudo pacman -S maven
sudo pacman -S mbedtls
sudo pacman -S mbox-importer
sudo pacman -S md4c
sudo pacman -S mdadm
sudo pacman -S media-player-info
sudo pacman -S mesa
sudo pacman -S mesa-demos
sudo pacman -S mesa-vdpau
sudo pacman -S meson
sudo pacman -S messagelib
sudo pacman -S metis
sudo pacman -S milou
sudo pacman -S minecraft-launcher
sudo pacman -S minicom
sudo pacman -S miniupnpc
sudo pacman -S minizip
sudo pacman -S minuet
sudo pacman -S mixxx
sudo pacman -S mjpegtools
sudo pacman -S mkinitcpio
sudo pacman -S mkinitcpio-busybox
sudo pacman -S mlt
sudo pacman -S mlt6
sudo pacman -S mobile-broadband-provider-info
sudo pacman -S modemmanager
sudo pacman -S modemmanager-qt
sudo pacman -S molequeue
sudo pacman -S monero
sudo pacman -S monero-gui
sudo pacman -S mono
sudo pacman -S mono-msbuild
sudo pacman -S motrix-git
sudo pacman -S movit
sudo pacman -S mpfr
sudo pacman -S mpg123
sudo pacman -S mplayer
sudo pacman -S mprime
sudo pacman -S mpv
sudo pacman -S msgpack-c
sudo pacman -S msr-tools
sudo pacman -S mtdev
sudo pacman -S mtools
sudo pacman -S mujs
sudo pacman -S mypaint-brushes1
sudo pacman -S nano
sudo pacman -S nautilus
sudo pacman -S ncurses
sudo pacman -S ndctl
sudo pacman -S neofetch
sudo pacman -S neon
sudo pacman -S neovim
sudo pacman -S nerd-fonts-agave
sudo pacman -S nerd-fonts-anonymous-pro
sudo pacman -S nerd-fonts-arimo
sudo pacman -S nerd-fonts-aurulent-sans-mono
sudo pacman -S nerd-fonts-bigblue-terminal
sudo pacman -S nerd-fonts-bitstream-vera-sans-mono
sudo pacman -S nerd-fonts-cascadia-code
sudo pacman -S nerd-fonts-code-new-roman
sudo pacman -S nerd-fonts-cousine
sudo pacman -S nerd-fonts-daddytimemono
sudo pacman -S nerd-fonts-dejavu-sans-mono
sudo pacman -S nerd-fonts-droid-sans-mono
sudo pacman -S nerd-fonts-fantasque-sans-mono
sudo pacman -S nerd-fonts-fira
sudo pacman -S nerd-fonts-fira-code
sudo pacman -S nerd-fonts-go
sudo pacman -S nerd-fonts-gohu
sudo pacman -S nerd-fonts-hack
sudo pacman -S nerd-fonts-hasklig
sudo pacman -S nerd-fonts-heavy-data
sudo pacman -S nerd-fonts-hermit
sudo pacman -S nerd-fonts-ia-writer
sudo pacman -S nerd-fonts-ibm-plex-mono
sudo pacman -S nerd-fonts-inconsolata
sudo pacman -S nerd-fonts-inconsolata-go
sudo pacman -S nerd-fonts-inconsolata-lgc
sudo pacman -S nerd-fonts-iosevka
sudo pacman -S nerd-fonts-jetbrains-mono
sudo pacman -S nerd-fonts-lekton
sudo pacman -S nerd-fonts-liberation
sudo pacman -S nerd-fonts-meslo-lg
sudo pacman -S nerd-fonts-monofur
sudo pacman -S nerd-fonts-monoid
sudo pacman -S nerd-fonts-mononoki
sudo pacman -S nerd-fonts-mplus
sudo pacman -S nerd-fonts-noto
sudo pacman -S nerd-fonts-opendyslexic
sudo pacman -S nerd-fonts-overpass
sudo pacman -S nerd-fonts-profont
sudo pacman -S nerd-fonts-proggycleantt
sudo pacman -S nerd-fonts-robotomono
sudo pacman -S nerd-fonts-share-tech-mono
sudo pacman -S nerd-fonts-source-code-pro
sudo pacman -S nerd-fonts-space-mono
sudo pacman -S nerd-fonts-terminus
sudo pacman -S nerd-fonts-tinos
sudo pacman -S nerd-fonts-ubuntu
sudo pacman -S nerd-fonts-ubuntu-mono
sudo pacman -S nerd-fonts-victor-mono
sudo pacman -S net-snmp
sudo pacman -S net-tools
sudo pacman -S netbeans
sudo pacman -S netpbm
sudo pacman -S netstandard-targeting-pack
sudo pacman -S nettle
sudo pacman -S network-manager-applet
sudo pacman -S networkmanager
sudo pacman -S networkmanager-qt
sudo pacman -S new-session-manager
sudo pacman -S nftables
sudo pacman -S nginx
sudo pacman -S nginx-mod-rtmp-git
sudo pacman -S ngspice
sudo pacman -S nilfs-utils
sudo pacman -S ninja
sudo pacman -S nm-connection-editor
sudo pacman -S nmap
sudo pacman -S node-gyp
sudo pacman -S nodejs
sudo pacman -S nodejs-nopt
sudo pacman -S nodemcu-pyflasher
sudo pacman -S noto-fonts
sudo pacman -S noto-fonts-cjk
sudo pacman -S noto-fonts-emoji
sudo pacman -S noto-fonts-emoji-blob
sudo pacman -S noto-fonts-extra
sudo pacman -S npm
sudo pacman -S npth
sudo pacman -S nspr
sudo pacman -S nss
sudo pacman -S ntfs-3g
sudo pacman -S numactl
sudo pacman -S nvidia-lts
sudo pacman -S nvidia-utils
sudo pacman -S oath-toolkit
sudo pacman -S obs-studio
sudo pacman -S ocaml
sudo pacman -S ocaml-compiler-libs
sudo pacman -S ocaml-csexp
sudo pacman -S ocaml-findlib
sudo pacman -S ocaml-result
sudo pacman -S ocl-icd
sudo pacman -S octopi
sudo pacman -S okular
sudo pacman -S onefetch
sudo pacman -S oniguruma
sudo pacman -S opam
sudo pacman -S openal
sudo pacman -S openbabel
sudo pacman -S opencascade
sudo pacman -S opencc
sudo pacman -S opencl-headers
sudo pacman -S opencl-mesa
sudo pacman -S opencl-nvidia
sudo pacman -S opencollada
sudo pacman -S opencolorio
sudo pacman -S opencolorio1
sudo pacman -S opencore-amr
sudo pacman -S opencv
sudo pacman -S openexr
sudo pacman -S openimagedenoise
sudo pacman -S openimageio
sudo pacman -S openjpeg2
sudo pacman -S openmpi
sudo pacman -S openresolv
sudo pacman -S openrgb
sudo pacman -S openshadinglanguage
sudo pacman -S openssh
sudo pacman -S openssl
sudo pacman -S openssl-1.0
sudo pacman -S opensubdiv
sudo pacman -S openvdb
sudo pacman -S openxr
sudo pacman -S opus
sudo pacman -S opusfile
sudo pacman -S orc
sudo pacman -S os-prober
sudo pacman -S osinfo-db
sudo pacman -S ossp
sudo pacman -S ostree
sudo pacman -S oxygen
sudo pacman -S p11-kit
sudo pacman -S p7zip
sudo pacman -S package-query
sudo pacman -S pacman
sudo pacman -S pacman-contrib
sudo pacman -S pacman-mirrorlist
sudo pacman -S pacmanlogviewer
sudo pacman -S pahole
sudo pacman -S palapeli
sudo pacman -S pam
sudo pacman -S pam-python
sudo pacman -S pambase
sudo pacman -S pango
sudo pacman -S pangomm
sudo pacman -S paper
sudo pacman -S papirus-icon-theme
sudo pacman -S parley
sudo pacman -S parted
sudo pacman -S partitionmanager
sudo pacman -S paru
sudo pacman -S pastebinit
sudo pacman -S patch
sudo pacman -S patchelf
sudo pacman -S pavucontrol
sudo pacman -S pciutils
sudo pacman -S pcre
sudo pacman -S pcre2
sudo pacman -S pcsclite
sudo pacman -S perf
sudo pacman -S perl
sudo pacman -S perl-clone
sudo pacman -S perl-encode-locale
sudo pacman -S perl-error
sudo pacman -S perl-file-listing
sudo pacman -S perl-html-parser
sudo pacman -S perl-html-tagset
sudo pacman -S perl-http-cookies
sudo pacman -S perl-http-daemon
sudo pacman -S perl-http-date
sudo pacman -S perl-http-message
sudo pacman -S perl-http-negotiate
sudo pacman -S perl-io-html
sudo pacman -S perl-ipc-run3
sudo pacman -S perl-libwww
sudo pacman -S perl-locale-gettext
sudo pacman -S perl-lwp-mediatypes
sudo pacman -S perl-mailtools
sudo pacman -S perl-net-http
sudo pacman -S perl-parse-yapp
sudo pacman -S perl-timedate
sudo pacman -S perl-try-tiny
sudo pacman -S perl-uri
sudo pacman -S perl-www-robotrules
sudo pacman -S perl-xml-parser
sudo pacman -S perl-xml-writer
sudo pacman -S phodav
sudo pacman -S phonon-qt5
sudo pacman -S phonon-qt5-gstreamer
sudo pacman -S php
sudo pacman -S picmi
sudo pacman -S picom
sudo pacman -S pim-data-exporter
sudo pacman -S pim-sieve-editor
sudo pacman -S pimcommon
sudo pacman -S pinentry
sudo pacman -S pipewire
sudo pacman -S pipewire-jack
sudo pacman -S pipewire-media-session
sudo pacman -S pixman
sudo pacman -S pkgconf
sudo pacman -S pkgfile
sudo pacman -S plasma-browser-integration
sudo pacman -S plasma-desktop
sudo pacman -S plasma-disks
sudo pacman -S plasma-firewall
sudo pacman -S plasma-framework
sudo pacman -S plasma-integration
sudo pacman -S plasma-nm
sudo pacman -S plasma-pa
sudo pacman -S plasma-sdk
sudo pacman -S plasma-systemmonitor
sudo pacman -S plasma-thunderbolt
sudo pacman -S plasma-vault
sudo pacman -S plasma-workspace
sudo pacman -S plasma-workspace-wallpapers
sudo pacman -S polkit
sudo pacman -S polkit-kde-agent
sudo pacman -S polkit-qt5
sudo pacman -S ponysay
sudo pacman -S poppler
sudo pacman -S poppler-data
sudo pacman -S poppler-glib
sudo pacman -S poppler-qt5
sudo pacman -S popt
sudo pacman -S portaudio
sudo pacman -S portmidi
sudo pacman -S portsmf
sudo pacman -S potrace
sudo pacman -S powerdevil
sudo pacman -S poxml
sudo pacman -S ppp
sudo pacman -S print-manager
sudo pacman -S prismatik
sudo pacman -S prison
sudo pacman -S procps-ng
sudo pacman -S protobuf
sudo pacman -S protobuf-c
sudo pacman -S proton
sudo pacman -S psmisc
sudo pacman -S psutils
sudo pacman -S ptex
sudo pacman -S pugixml
sudo pacman -S pulseaudio
sudo pacman -S pulseaudio-alsa
sudo pacman -S pulseaudio-bluetooth
sudo pacman -S pulseaudio-equalizer
sudo pacman -S pulseaudio-equalizer-ladspa
sudo pacman -S pulseaudio-jack
sudo pacman -S pulseaudio-lirc
sudo pacman -S pulseaudio-qt
sudo pacman -S pulseaudio-rtp
sudo pacman -S pulseaudio-zeroconf
sudo pacman -S pulsemixer
sudo pacman -S purpose
sudo pacman -S pybind11
sudo pacman -S pycharm-community-edition
sudo pacman -S pyrit
sudo pacman -S pystring
sudo pacman -S python
sudo pacman -S python-anytree
sudo pacman -S python-appdirs
sudo pacman -S python-argcomplete
sudo pacman -S python-asn1crypto
sudo pacman -S python-attrs
sudo pacman -S python-aubio
sudo pacman -S python-automat
sudo pacman -S python-babel
sudo pacman -S python-backcall
sudo pacman -S python-beaker
sudo pacman -S python-bitstring
sudo pacman -S python-cachecontrol
sudo pacman -S python-cairo
sudo pacman -S python-cffi
sudo pacman -S python-chardet
sudo pacman -S python-click
sudo pacman -S python-colorama
sudo pacman -S python-constantly
sudo pacman -S python-contextlib2
sudo pacman -S python-cryptography
sudo pacman -S python-dateutil
sudo pacman -S python-debugpy
sudo pacman -S python-decorator
sudo pacman -S python-distlib
sudo pacman -S python-distro
sudo pacman -S python-dlib
sudo pacman -S python-dnspython
sudo pacman -S python-docopt
sudo pacman -S python-docutils
sudo pacman -S python-ecdsa
sudo pacman -S python-epc
sudo pacman -S python-evdev
sudo pacman -S python-face_recognition
sudo pacman -S python-face_recognition_models
sudo pacman -S python-feedparser
sudo pacman -S python-flask
sudo pacman -S python-future
sudo pacman -S python-gobject
sudo pacman -S python-grip
sudo pacman -S python-html5lib
sudo pacman -S python-httplib2
sudo pacman -S python-hyperlink
sudo pacman -S python-idna
sudo pacman -S python-imagesize
sudo pacman -S python-importlib-metadata
sudo pacman -S python-incremental
sudo pacman -S python-ipykernel
sudo pacman -S python-itsdangerous
sudo pacman -S python-jedi
sudo pacman -S python-jinja
sudo pacman -S python-jsonrpc-server
sudo pacman -S python-jupyter_client
sudo pacman -S python-jupyter_core
sudo pacman -S python-language-server
sudo pacman -S python-lxml
sudo pacman -S python-mako
sudo pacman -S python-markdown
sudo pacman -S python-markupsafe
sudo pacman -S python-matplotlib-inline
sudo pacman -S python-more-itertools
sudo pacman -S python-msgpack
sudo pacman -S python-nautilus
sudo pacman -S python-numpy
sudo pacman -S python-opencv
sudo pacman -S python-ordered-set
sudo pacman -S python-packaging
sudo pacman -S python-parso
sudo pacman -S python-path-and-address
sudo pacman -S python-pep517
sudo pacman -S python-pexpect
sudo pacman -S python-pickleshare
sudo pacman -S python-pillow
sudo pacman -S python-pip
sudo pacman -S python-pluggy
sudo pacman -S python-ply
sudo pacman -S python-prettytable
sudo pacman -S python-progress
sudo pacman -S python-prompt_toolkit
sudo pacman -S python-psutil
sudo pacman -S python-ptyprocess
sudo pacman -S python-pyaes
sudo pacman -S python-pyalsa
sudo pacman -S python-pycparser
sudo pacman -S python-pygments
sudo pacman -S python-pyhamcrest
sudo pacman -S python-pyinotify
sudo pacman -S python-pyopenssl
sudo pacman -S python-pyparsing
sudo pacman -S python-pyqt5
sudo pacman -S python-pyqt5-sip
sudo pacman -S python-pyqt5-webengine
sudo pacman -S python-pyserial
sudo pacman -S python-pyte
sudo pacman -S python-pytz
sudo pacman -S python-pyxdg
sudo pacman -S python-pyzmq
sudo pacman -S python-qrcode
sudo pacman -S python-qtconsole
sudo pacman -S python-qtpy
sudo pacman -S python-reedsolo
sudo pacman -S python-requests
sudo pacman -S python-resolvelib
sudo pacman -S python-retrying
sudo pacman -S python-scipy
sudo pacman -S python-setuptools
sudo pacman -S python-sexpdata
sudo pacman -S python-sgmllib
sudo pacman -S python-shiboken2
sudo pacman -S python-sip4
sudo pacman -S python-six
sudo pacman -S python-snowballstemmer
sudo pacman -S python-sphinx
sudo pacman -S python-sphinx-alabaster-theme
sudo pacman -S python-sphinxcontrib-applehelp
sudo pacman -S python-sphinxcontrib-devhelp
sudo pacman -S python-sphinxcontrib-htmlhelp
sudo pacman -S python-sphinxcontrib-jsmath
sudo pacman -S python-sphinxcontrib-qthelp
sudo pacman -S python-sphinxcontrib-serializinghtml
sudo pacman -S python-systemd
sudo pacman -S python-sysv_ipc
sudo pacman -S python-termcolor
sudo pacman -S python-toml
sudo pacman -S python-tomli
sudo pacman -S python-tornado
sudo pacman -S python-traitlets
sudo pacman -S python-twisted
sudo pacman -S python-typing_extensions
sudo pacman -S python-ujson
sudo pacman -S python-urllib3
sudo pacman -S python-wcwidth
sudo pacman -S python-webencodings
sudo pacman -S python-werkzeug
sudo pacman -S python-wxpython
sudo pacman -S python-xlib
sudo pacman -S python-yaml
sudo pacman -S python-zipp
sudo pacman -S python-zope-interface
sudo pacman -S python2
sudo pacman -S python2-appdirs
sudo pacman -S python2-asn1crypto
sudo pacman -S python2-backports
sudo pacman -S python2-cachecontrol
sudo pacman -S python2-cffi
sudo pacman -S python2-chardet
sudo pacman -S python2-colorama
sudo pacman -S python2-configparser
sudo pacman -S python2-contextlib2
sudo pacman -S python2-cryptography
sudo pacman -S python2-distlib
sudo pacman -S python2-distro
sudo pacman -S python2-enum34
sudo pacman -S python2-html5lib
sudo pacman -S python2-idna
sudo pacman -S python2-importlib-metadata
sudo pacman -S python2-ipaddress
sudo pacman -S python2-msgpack
sudo pacman -S python2-ordered-set
sudo pacman -S python2-packaging
sudo pacman -S python2-pathlib2
sudo pacman -S python2-pep517
sudo pacman -S python2-pip
sudo pacman -S python2-ply
sudo pacman -S python2-progress
sudo pacman -S python2-pycparser
sudo pacman -S python2-pyopenssl
sudo pacman -S python2-pyparsing
sudo pacman -S python2-requests
sudo pacman -S python2-resolvelib
sudo pacman -S python2-retrying
sudo pacman -S python2-scandir
sudo pacman -S python2-setuptools
sudo pacman -S python2-six
sudo pacman -S python2-toml
sudo pacman -S python2-urllib3
sudo pacman -S python2-webencodings
sudo pacman -S python2-zipp
sudo pacman -S qca-qt5
sudo pacman -S qemu
sudo pacman -S qemu-arch-extra
sudo pacman -S qemu-block-gluster
sudo pacman -S qemu-block-iscsi
sudo pacman -S qemu-block-rbd
sudo pacman -S qgpgme
sudo pacman -S qhull
sudo pacman -S qpdf
sudo pacman -S qqc2-desktop-style
sudo pacman -S qrencode
sudo pacman -S qt-gstreamer
sudo pacman -S qt5-base
sudo pacman -S qt5-declarative
sudo pacman -S qt5-graphicaleffects
sudo pacman -S qt5-imageformats
sudo pacman -S qt5-location
sudo pacman -S qt5-multimedia
sudo pacman -S qt5-networkauth
sudo pacman -S qt5-quickcontrols
sudo pacman -S qt5-quickcontrols2
sudo pacman -S qt5-script
sudo pacman -S qt5-sensors
sudo pacman -S qt5-serialport
sudo pacman -S qt5-speech
sudo pacman -S qt5-svg
sudo pacman -S qt5-tools
sudo pacman -S qt5-wayland
sudo pacman -S qt5-webchannel
sudo pacman -S qt5-webengine
sudo pacman -S qt5-webkit
sudo pacman -S qt5-x11extras
sudo pacman -S qt5-xmlpatterns
sudo pacman -S qt5pas
sudo pacman -S qtermwidget
sudo pacman -S qtkeychain-qt5
sudo pacman -S quazip
sudo pacman -S qv2ray
sudo pacman -S qv2ray-plugin-trojan
sudo pacman -S radeontool
sudo pacman -S ragel
sudo pacman -S rainbarf-git
sudo pacman -S ranger
sudo pacman -S rapidjson
sudo pacman -S raptor
sudo pacman -S rar
sudo pacman -S rasqal
sudo pacman -S rav1e
sudo pacman -S rclone
sudo pacman -S rclone-browser
sudo pacman -S re2
sudo pacman -S read-edid
sudo pacman -S readline
sudo pacman -S reaper-bin
sudo pacman -S recode
sudo pacman -S recordmydesktop
sudo pacman -S redland
sudo pacman -S reflector
sudo pacman -S reiserfsprogs
sudo pacman -S remmina
sudo pacman -S rest
sudo pacman -S rhash
sudo pacman -S rime-bopomofo
sudo pacman -S rime-cangjie
sudo pacman -S rime-emoji
sudo pacman -S rime-essay
sudo pacman -S rime-luna-pinyin
sudo pacman -S rime-prelude
sudo pacman -S rime-stroke
sudo pacman -S rime-terra-pinyin
sudo pacman -S ripgrep
sudo pacman -S rnnoise
sudo pacman -S roccat-tools-common
sudo pacman -S roccat-tools-kone
sudo pacman -S roccat-tools-koneplus
sudo pacman -S roccat-tools-konepure
sudo pacman -S roccat-tools-konextd
sudo pacman -S rocs
sudo pacman -S rofi
sudo pacman -S rpcbind
sudo pacman -S rsync
sudo pacman -S rtaudio
sudo pacman -S rtkit
sudo pacman -S rtmpdump
sudo pacman -S rttr
sudo pacman -S rubberband
sudo pacman -S ruby
sudo pacman -S ruby-diff-lcs
sudo pacman -S ruby-irb
sudo pacman -S ruby-manpages
sudo pacman -S ruby-optimist
sudo pacman -S ruby-paint
sudo pacman -S ruby-rainbow
sudo pacman -S ruby-rdoc
sudo pacman -S ruby-reline
sudo pacman -S ruby-rspec
sudo pacman -S ruby-rspec-core
sudo pacman -S ruby-rspec-expectations
sudo pacman -S ruby-rspec-mocks
sudo pacman -S ruby-rspec-support
sudo pacman -S ruby-term-ansicolor
sudo pacman -S ruby-tins
sudo pacman -S rubygems
sudo pacman -S run-parts
sudo pacman -S runc
sudo pacman -S rustup
sudo pacman -S samba
sudo pacman -S sane
sudo pacman -S sbc
sudo pacman -S scrcpy
sudo pacman -S screen
sudo pacman -S screenfetch
sudo pacman -S screenkey
sudo pacman -S scrot
sudo pacman -S sd
sudo pacman -S sddm
sudo pacman -S sddm-kcm
sudo pacman -S sddm-sugar-light
sudo pacman -S sdl
sudo pacman -S sdl2
sudo pacman -S sdl2_image
sudo pacman -S sdl2_mixer
sudo pacman -S sdl2_ttf
sudo pacman -S sdl_image
sudo pacman -S sdl_mixer
sudo pacman -S sdl_net
sudo pacman -S sdl_sound
sudo pacman -S sdl_ttf
sudo pacman -S seabios
sudo pacman -S sed
sudo pacman -S semver
sudo pacman -S serd
sudo pacman -S sfml
sudo pacman -S shaderc
sudo pacman -S shadow
sudo pacman -S shared-mime-info
sudo pacman -S signon-kwallet-extension
sudo pacman -S signon-plugin-oauth2
sudo pacman -S signon-ui
sudo pacman -S signond
sudo pacman -S slang
sudo pacman -S smartmontools
sudo pacman -S smbclient
sudo pacman -S smpeg
sudo pacman -S snappy
sudo pacman -S sndio
sudo pacman -S snes9x-gtk
sudo pacman -S socat
sudo pacman -S solid
sudo pacman -S sonnet
sudo pacman -S sord
sudo pacman -S sound-theme-freedesktop
sudo pacman -S soundtouch
sudo pacman -S source-highlight
sudo pacman -S sox
sudo pacman -S spandsp
sudo pacman -S spectacle
sudo pacman -S speedtest-cli
sudo pacman -S speex
sudo pacman -S speexdsp
sudo pacman -S spglib
sudo pacman -S spice
sudo pacman -S spice-gtk
sudo pacman -S spirv-tools
sudo pacman -S sqlite
sudo pacman -S sratom
sudo pacman -S srt
sudo pacman -S sshfs
sudo pacman -S startup-notification
sudo pacman -S steam
sudo pacman -S steam-native-runtime
sudo pacman -S step
sudo pacman -S stk
sudo pacman -S sudo
sudo pacman -S suil
sudo pacman -S suitesparse
sudo pacman -S sunloginclient
sudo pacman -S svgpart
sudo pacman -S svt-av1
sudo pacman -S svt-hevc
sudo pacman -S sweeper
sudo pacman -S swh-plugins
sudo pacman -S syndication
sudo pacman -S syntax-highlighting
sudo pacman -S sysfsutils
sudo pacman -S systemd
sudo pacman -S systemd-libs
sudo pacman -S systemd-swap
sudo pacman -S systemd-sysvcompat
sudo pacman -S systemsettings
sudo pacman -S taglib
sudo pacman -S talloc
sudo pacman -S tar
sudo pacman -S tbb
sudo pacman -S tcl
sudo pacman -S tdb
sudo pacman -S tdlib
sudo pacman -S teamspeak3
sudo pacman -S teamspeak3-server
sudo pacman -S telegram-desktop
sudo pacman -S telepathy-accounts-signon
sudo pacman -S telepathy-farstream
sudo pacman -S telepathy-glib
sudo pacman -S telepathy-kde-accounts-kcm
sudo pacman -S telepathy-kde-approver
sudo pacman -S telepathy-kde-auth-handler
sudo pacman -S telepathy-kde-call-ui
sudo pacman -S telepathy-kde-common-internals
sudo pacman -S telepathy-kde-contact-list
sudo pacman -S telepathy-kde-contact-runner
sudo pacman -S telepathy-kde-desktop-applets
sudo pacman -S telepathy-kde-filetransfer-handler
sudo pacman -S telepathy-kde-integration-module
sudo pacman -S telepathy-kde-send-file
sudo pacman -S telepathy-kde-text-ui
sudo pacman -S telepathy-logger
sudo pacman -S telepathy-logger-qt
sudo pacman -S telepathy-mission-control
sudo pacman -S telepathy-qt
sudo pacman -S tepl
sudo pacman -S terraria-server
sudo pacman -S tevent
sudo pacman -S texinfo
sudo pacman -S thefuck
sudo pacman -S thin-provisioning-tools
sudo pacman -S threadweaver
sudo pacman -S tigervnc
sudo pacman -S tinyxml
sudo pacman -S tk
sudo pacman -S tldr
sudo pacman -S tlp
sudo pacman -S tlp-rdw
sudo pacman -S tlpui-git
sudo pacman -S tmux
sudo pacman -S todesk-bin
sudo pacman -S totem-pl-parser
sudo pacman -S traceroute
sudo pacman -S tracker3
sudo pacman -S tracker3-miners
sudo pacman -S trash-cli
sudo pacman -S tree-sitter
sudo pacman -S trojan
sudo pacman -S tslib
sudo pacman -S ttf-dejavu
sudo pacman -S ttf-droid
sudo pacman -S ttf-hack
sudo pacman -S ttf-inconsolata
sudo pacman -S ttf-jetbrains-mono
sudo pacman -S ttf-joypixels
sudo pacman -S ttf-liberation
sudo pacman -S ttf-linux-libertine
sudo pacman -S ttf-monaco
sudo pacman -S ttf-ms-fonts
sudo pacman -S ttf-nerd-fonts-symbols
sudo pacman -S ttf-opensans
sudo pacman -S ttf-sarasa-gothic
sudo pacman -S ttf-symbola
sudo pacman -S ttf-ubuntu-font-family
sudo pacman -S ttf-unifont
sudo pacman -S twolame
sudo pacman -S tzdata
sudo pacman -S uchardet
sudo pacman -S udftools
sudo pacman -S udisks2
sudo pacman -S ueberzug
sudo pacman -S ufw
sudo pacman -S umbrello
sudo pacman -S unbound
sudo pacman -S unibilium
sudo pacman -S unicode-character-database
sudo pacman -S unicode-cldr
sudo pacman -S unicode-cldr-annotations
sudo pacman -S unicode-emoji
sudo pacman -S unityhub
sudo pacman -S unzip
sudo pacman -S upower
sudo pacman -S usbmuxd
sudo pacman -S usbredir
sudo pacman -S usbutils
sudo pacman -S util-linux
sudo pacman -S util-linux-libs
sudo pacman -S utools
sudo pacman -S v2ray
sudo pacman -S v2ray-domain-list-community
sudo pacman -S v2ray-geoip
sudo pacman -S v2raya
sudo pacman -S v4l-utils
sudo pacman -S v4l2loopback-dc-dkms
sudo pacman -S v4l2loopback-dkms
sudo pacman -S vala
sudo pacman -S vamp-plugin-sdk
sudo pacman -S vde2
sudo pacman -S vdpauinfo
sudo pacman -S ventoy-bin
sudo pacman -S vi
sudo pacman -S vid.stab
sudo pacman -S vim
sudo pacman -S vim-runtime
sudo pacman -S virglrenderer
sudo pacman -S virt-install
sudo pacman -S virt-manager
sudo pacman -S virtio-win
sudo pacman -S virtualbox
sudo pacman -S virtualbox-host-dkms
sudo pacman -S visual-studio-code-bin
sudo pacman -S vkd3d
sudo pacman -S vlc
sudo pacman -S vmaf
sudo pacman -S volume_key
sudo pacman -S vte-common
sudo pacman -S vte3
sudo pacman -S vtk
sudo pacman -S vulkan-headers
sudo pacman -S vulkan-icd-loader
sudo pacman -S vulkan-radeon
sudo pacman -S vulkan-tools
sudo pacman -S w3m
sudo pacman -S wavpack
sudo pacman -S wayland
sudo pacman -S wayland-protocols
sudo pacman -S webkit2gtk
sudo pacman -S webp-pixbuf-loader
sudo pacman -S webrtc-audio-processing
sudo pacman -S weechat
sudo pacman -S wget
sudo pacman -S which
sudo pacman -S whois
sudo pacman -S wildmidi
sudo pacman -S wine-mono
sudo pacman -S wine-valve
sudo pacman -S winetricks
sudo pacman -S wireless-regdb
sudo pacman -S wl-clipboard
sudo pacman -S wmctrl
sudo pacman -S woff2
sudo pacman -S wol
sudo pacman -S wpa_supplicant
sudo pacman -S wpebackend-fdo
sudo pacman -S wqy-bitmapfont
sudo pacman -S wqy-microhei
sudo pacman -S wqy-microhei-lite
sudo pacman -S wqy-zenhei
sudo pacman -S wxgtk-common
sudo pacman -S wxgtk3
sudo pacman -S x11vnc
sudo pacman -S x264
sudo pacman -S x265
sudo pacman -S x86_energy_perf_policy
sudo pacman -S xapian-core
sudo pacman -S xaw3d
sudo pacman -S xcb-imdkit
sudo pacman -S xcb-proto
sudo pacman -S xcb-util
sudo pacman -S xcb-util-cursor
sudo pacman -S xcb-util-image
sudo pacman -S xcb-util-keysyms
sudo pacman -S xcb-util-renderutil
sudo pacman -S xcb-util-wm
sudo pacman -S xcb-util-xrm
sudo pacman -S xclip
sudo pacman -S xdg-dbus-proxy
sudo pacman -S xdg-desktop-portal
sudo pacman -S xdg-desktop-portal-kde
sudo pacman -S xdg-user-dirs
sudo pacman -S xdg-utils
sudo pacman -S xdotool
sudo pacman -S xerces-c
sudo pacman -S xf86-input-evdev
sudo pacman -S xf86-input-libinput
sudo pacman -S xf86-input-synaptics
sudo pacman -S xf86-input-vmmouse
sudo pacman -S xf86-input-void
sudo pacman -S xf86-video-amdgpu
sudo pacman -S xf86-video-ati
sudo pacman -S xf86-video-dummy
sudo pacman -S xf86-video-fbdev
sudo pacman -S xf86-video-intel
sudo pacman -S xf86-video-nouveau
sudo pacman -S xf86-video-openchrome
sudo pacman -S xf86-video-qxl
sudo pacman -S xf86-video-vesa
sudo pacman -S xf86-video-vmware
sudo pacman -S xf86-video-voodoo
sudo pacman -S xfce4-notifyd
sudo pacman -S xfce4-power-manager
sudo pacman -S xfconf
sudo pacman -S xfsprogs
sudo pacman -S xjadeo
sudo pacman -S xkeyboard-config
sudo pacman -S xmlsec
sudo pacman -S xmrig
sudo pacman -S xorg-bdftopcf
sudo pacman -S xorg-docs
sudo pacman -S xorg-font-util
sudo pacman -S xorg-fonts-100dpi
sudo pacman -S xorg-fonts-75dpi
sudo pacman -S xorg-fonts-alias-100dpi
sudo pacman -S xorg-fonts-alias-75dpi
sudo pacman -S xorg-fonts-encodings
sudo pacman -S xorg-iceauth
sudo pacman -S xorg-mkfontscale
sudo pacman -S xorg-server
sudo pacman -S xorg-server-common
sudo pacman -S xorg-server-devel
sudo pacman -S xorg-server-xephyr
sudo pacman -S xorg-server-xnest
sudo pacman -S xorg-server-xvfb
sudo pacman -S xorg-sessreg
sudo pacman -S xorg-setxkbmap
sudo pacman -S xorg-smproxy
sudo pacman -S xorg-util-macros
sudo pacman -S xorg-x11perf
sudo pacman -S xorg-xauth
sudo pacman -S xorg-xcmsdb
sudo pacman -S xorg-xcursorgen
sudo pacman -S xorg-xdpyinfo
sudo pacman -S xorg-xdriinfo
sudo pacman -S xorg-xev
sudo pacman -S xorg-xgamma
sudo pacman -S xorg-xhost
sudo pacman -S xorg-xinit
sudo pacman -S xorg-xinput
sudo pacman -S xorg-xkbcomp
sudo pacman -S xorg-xkbevd
sudo pacman -S xorg-xkbutils
sudo pacman -S xorg-xkill
sudo pacman -S xorg-xlsatoms
sudo pacman -S xorg-xlsclients
sudo pacman -S xorg-xmessage
sudo pacman -S xorg-xmodmap
sudo pacman -S xorg-xpr
sudo pacman -S xorg-xprop
sudo pacman -S xorg-xrandr
sudo pacman -S xorg-xrdb
sudo pacman -S xorg-xrefresh
sudo pacman -S xorg-xset
sudo pacman -S xorg-xsetroot
sudo pacman -S xorg-xvinfo
sudo pacman -S xorg-xwayland
sudo pacman -S xorg-xwd
sudo pacman -S xorg-xwininfo
sudo pacman -S xorg-xwud
sudo pacman -S xorgproto
sudo pacman -S xplane-sdk-devel
sudo pacman -S xray
sudo pacman -S xray-domain-list-community
sudo pacman -S xray-geoip
sudo pacman -S xsel
sudo pacman -S xtensa-lx106-elf-gcc-bin
sudo pacman -S xvidcore
sudo pacman -S xxhash
sudo pacman -S xz
sudo pacman -S yajl
sudo pacman -S yakuake
sudo pacman -S yaml-cpp
sudo pacman -S yaourt
sudo pacman -S yarn
sudo pacman -S yasm
sudo pacman -S yelp-tools
sudo pacman -S yelp-xsl
sudo pacman -S you-get
sudo pacman -S yubico-c
sudo pacman -S yubico-c-client
sudo pacman -S yubikey-personalization
sudo pacman -S zbar
sudo pacman -S zenity
sudo pacman -S zeroconf-ioslave
sudo pacman -S zeromq
sudo pacman -S zile
sudo pacman -S zimg
sudo pacman -S zip
sudo pacman -S zita-alsa-pcmi
sudo pacman -S zita-resampler
sudo pacman -S zlib
sudo pacman -S zsh
sudo pacman -S zstd
sudo pacman -S zvbi
sudo pacman -S zxing-cpp
